media:
  input: assets/images
  output: /assets/images

content:
  - name: projects
    label: Projects (EN)
    type: collection
    path: _projects
    format: yaml-frontmatter
    fields:
      - name: title
        label: Map Title
        type: string
      - name: description
        label: Short Description
        type: string
      - name: download_url
        label: Download Link
        type: string
      - name: year
        label: Release Year
        type: number
      - name: languages
        label: Language(s)
        type: string
      - name: players
        label: Player Count
        type: string
      - name: mods
        label: Mods Required
        type: string
      - name: release_date
        label: Release Date
        type: date
      - name: update_date
        label: Last Updated
        type: date
      - name: project_tags
        label: Tags
        type: string
      - name: media
        label: Media
        type: block
        list: true
        blocks:
          - name: asset
            label: Media Asset
            fields:
              - name: type
                label: Type
                type: string
              - name: src
                label: Link
                type: string
      - name: layout
        label: Page Layout
        type: string
        default: project
      - name: body
        label: Description
        type: rich-text

  - name: ru_projects
    label: Projects (RU)
    type: collection
    path: _ru_projects
    format: yaml-frontmatter
    fields:
      - name: title
        label: Map Title
        type: string
      - name: body
        label: Description
        type: rich-text

  - name: members
    label: Team Members
    type: collection
    path: _members
    format: yaml-frontmatter
    fields:
      - name: name
        label: Member Name
        type: string
      - name: role
        label: Role
        type: string